name: Run Tests

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: todo-app/backend/package-lock.json

    - name: Install dependencies
      run: |
        cd todo-app/backend
        npm ci

    - name: Run tests
      run: |
        cd todo-app/backend
        npm test

    - name: Run tests with coverage
      run: |
        cd todo-app/backend
        npm run test:coverage

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./todo-app/backend/coverage/lcov.info
        flags: backend
        name: backend-coverage
        fail_ci_if_error: false
